#!/usr/bin/ansible-playbook
---
# -----------------------------------------------------------------------------

- name: bootstrap
  gather_facts: no
  hosts: localhost

  tasks:
    - name: ensure ssh key pair has been created
      command: |
        /usr/bin/ssh-keygen -f /data/id_rsa -q -C "" -N ""
      args:
        creates: /data/id_rsa
      tags:
        - keypair

    - name: ensure terraform infrastructure has been built
      terraform:
        project_path: "./tf/"
        state: present
      tags:
        - terraform
        - infra

  roles:
    - inventory

# -----------------------------------------------------------------------------

- name: prepare hosts
  gather_facts: no
  hosts:
    - tower
    - rhel
  become: yes

  handlers:
    - name: reboot hosts
      reboot:
      listen: reboot

    - name: wait for hosts
      wait_for_connection:
        sleep: 15
      listen: reboot

  tasks:
    - name: ensure hosts are reachable
      wait_for_connection:
        sleep: 15

    - name: ensure hosts are updated
      yum:
        name: '*'
        state: latest
      notify: reboot
      async: 500
      poll: 5
      register: yum_sleeper

    - name: wait for update to finish
      async_status:
        jid: "{{ yum_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 500
      delay: 1

# -----------------------------------------------------------------------------

- name: install - ansible tower
  gather_facts: yes
  hosts: tower_grp
  become: yes

  roles:
    - tower
    - name: tower-init
      tags: tower

# -----------------------------------------------------------------------------

- name: install - rhel nodes
  gather_facts: yes
  hosts: rhel
  become: yes

  roles:
    - name: towercli
      tags: rhel
    - name: ansible
      tags: rhel
...
